/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class home_lib_windows_odbc_OdbcBridge */

#ifndef _Included_home_lib_windows_odbc_OdbcBridge
#define _Included_home_lib_windows_odbc_OdbcBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef home_lib_windows_odbc_OdbcBridge_DBVT_NULL
#define home_lib_windows_odbc_OdbcBridge_DBVT_NULL 0L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_BOOL
#define home_lib_windows_odbc_OdbcBridge_DBVT_BOOL 1L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_UCHAR
#define home_lib_windows_odbc_OdbcBridge_DBVT_UCHAR 2L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_SHORT
#define home_lib_windows_odbc_OdbcBridge_DBVT_SHORT 3L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_LONG
#define home_lib_windows_odbc_OdbcBridge_DBVT_LONG 4L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_SINGLE
#define home_lib_windows_odbc_OdbcBridge_DBVT_SINGLE 5L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_DOUBLE
#define home_lib_windows_odbc_OdbcBridge_DBVT_DOUBLE 6L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_DATE
#define home_lib_windows_odbc_OdbcBridge_DBVT_DATE 7L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_STRING
#define home_lib_windows_odbc_OdbcBridge_DBVT_STRING 8L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_BINARY
#define home_lib_windows_odbc_OdbcBridge_DBVT_BINARY 9L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_ASTRING
#define home_lib_windows_odbc_OdbcBridge_DBVT_ASTRING 10L
#undef home_lib_windows_odbc_OdbcBridge_DBVT_WSTRING
#define home_lib_windows_odbc_OdbcBridge_DBVT_WSTRING 11L
#undef home_lib_windows_odbc_OdbcBridge_DBEX_DATA
#define home_lib_windows_odbc_OdbcBridge_DBEX_DATA 0L
#undef home_lib_windows_odbc_OdbcBridge_DBEX_FORMAT
#define home_lib_windows_odbc_OdbcBridge_DBEX_FORMAT 1L
/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    GetDrivers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_home_lib_windows_odbc_OdbcBridge_GetDrivers
  (JNIEnv *, jobject);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    executeSelect
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_executeSelect
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    executeSql
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_executeSql
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    adoBuildConnection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_lib_windows_odbc_OdbcBridge_adoBuildConnection
  (JNIEnv *, jobject);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    openDb
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_home_lib_windows_odbc_OdbcBridge_openDb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    openHasRecord
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_home_lib_windows_odbc_OdbcBridge_openHasRecord
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    rsIsEOF
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_home_lib_windows_odbc_OdbcBridge_rsIsEOF
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    rsIsOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_home_lib_windows_odbc_OdbcBridge_rsIsOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    cleanRS
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_home_lib_windows_odbc_OdbcBridge_cleanRS
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    closeDB
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_home_lib_windows_odbc_OdbcBridge_closeDB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getInt
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getInt__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getLong
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getLong__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getDouble
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getDouble__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_lib_windows_odbc_OdbcBridge_getString__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getStringBSTR
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_home_lib_windows_odbc_OdbcBridge_getStringBSTR__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getInt
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getInt__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getLong
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getLong__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getDouble
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_getDouble__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_lib_windows_odbc_OdbcBridge_getString__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getStringBSTR
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_home_lib_windows_odbc_OdbcBridge_getStringBSTR__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    getFields
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_home_lib_windows_odbc_OdbcBridge_getFields
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    moveNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_home_lib_windows_odbc_OdbcBridge_moveNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     home_lib_windows_odbc_OdbcBridge
 * Method:    execute
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_home_lib_windows_odbc_OdbcBridge_execute
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
